name: Swift CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        xcode: [ "15.4", "16.1" ]

    steps:
    - uses: actions/checkout@v4

    - name: Select Xcode ${{ matrix.xcode }}
      run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app

    - name: Build
      run: swift build -v

    - name: Run tests
      run: swift test -v
